/** The build list — one numbered line per change, naming the file it touches. */
export const BUILD = [
  { part: 'The apartment window', from: 'decisions 1–3', items: [
    { n: 1, t: 'The plan sits beside the details above 800px and becomes a tab below it',
      f: ['src/components/apartment/ApartmentDetailDrawer.tsx'],
      d: `Add a subscribed width test at <code>(min-width: 800px)</code> built the way <code>src/data/usePhone.ts</code> is — a matchMedia listener, never a value cached at mount, because a Fold changes width while the window is open. <code>planSideOn</code> requires that test AND <code>planPaneOn</code>. Below 800 there is no side pane and the <strong>Plan tab</strong> is shown — that tab already exists via <code>planPane('tab')</code> but is gated on <code>isPhone</code>; gate it on the new test instead. The existing <code>planW</code> / <code>modalH</code> screen cap stays for the side case. Standing rule preserved: the Plan tab never jumps into the markup studio — <em>Mark up</em> inside the pane is the only way in.` },
    { n: 2, t: 'The plan’s tab strip appears only in the markup studio',
      f: ['src/components/plans/PlanAnnotator.tsx', 'src/components/plans/PlanTabs.tsx'],
      d: `Render <code>PlanTabsStrip</code> only when the annotator is neither <code>readOnly</code> nor <code>embedded</code>. That one condition covers every preview the owner named — the drawer side pane, the phone Plan tab, the wallboard and the worker’s portal — and leaves the strip exactly as it is in the full-screen studio. Keep the tab state itself (<code>loadTabState</code> / <code>saveTabState</code>, <code>plan_tabs_&lt;apartmentId&gt;</code>); a preview simply does not draw the strip, and its <code>+</code> and per-tab close do not exist there.` },
    { n: 3, t: 'Drive and Zoho stay side by side; the text hides behind the field’s edge',
      f: ['src/components/ui/LinkField.tsx', 'src/components/apartment/ApartmentDetailDrawer.tsx'],
      d: `The cause is in <code>LinkField</code>’s EMPTY state (the dashed add-a-link button): it renders <code>&lt;Link2/&gt; {placeholder}</code> as a bare text node in a flex row with no <code>min-w-0</code>, so the long URL sets the button’s min-content width and pushes it past its grid column into its neighbour. Wrap the placeholder in a span with <code>min-w-0 flex-1 overflow-hidden whitespace-nowrap text-left</code>, and give the button <code>min-w-0 overflow-hidden</code>. Fade rather than ellipsis: <code>mask-image: linear-gradient(to right, #000 calc(100% - 22px), transparent)</code> plus the <code>-webkit-</code> twin, mirrored under RTL. In the drawer, add <code>min-w-0</code> to each grid CELL as well — a grid item floors at its content’s min-width otherwise. <strong>The grid keeps <code>grid-cols-1 md:grid-cols-2</code></strong>; it must never collapse to one column at any width (explicit owner decision — they never stack).` },
  ] },
  { part: 'The building diagram', from: 'decisions 4–5', items: [
    { n: 4, t: 'Below 900px the diagram shows one building at a time',
      f: ['src/pages/ProjectDiagramPage.tsx'],
      d: `The page already has <code>usePhone()</code> at <code>(max-width: 767px)</code>. Add a second subscribed test — call it <code>useNarrow()</code> at <code>(max-width: 899px)</code> — and drive the one-building resolution from it: <code>phoneBuilding</code> currently gates on <code>isPhone</code>, so gate it on <code>isNarrow</code>. The A1 / A2 / A3 tab row (today inside the <code>md:hidden</code> bar) shows up to 899px. Above 900 nothing changes at all. <strong>Keep <code>BuildingDiagram</code>’s <code>phone</code> prop on the real phone test</strong> — taller rows and bigger type is a different question from how many buildings are on screen.` },
    { n: 5, t: 'Below 900px: the Filters button, and one stage bar in place of the bubbles',
      f: ['src/pages/ProjectDiagramPage.tsx', 'src/components/diagram/StageBar.tsx (new)'],
      d: `Below 900 show the existing <code>md:hidden</code> bar (search + Filters + building tabs) and hide the desktop bar and the stage-count strip. Those three are keyed to <code>md</code> today (<code>md:hidden</code> / <code>hidden md:block</code> / <code>hidden md:flex</code>); move them to a custom Tailwind screen at 900 rather than to inline <code>display</code> driven by React, so the CSS keeps working while React is deciding.<br><br>New <code>StageBar</code>: one row, one flex segment per stage with <code>flex: &lt;count&gt;</code> and the stage’s own colour, the count written inside a segment wide enough to hold it. Pressing a segment toggles that stage in the page’s existing <code>activeStageIds</code>. A line above it reads the total; the stage names with colour dots wrap beneath. <strong>The separate row of bare numbers is deleted</strong> — the counts now live in the bar. Counts come through <code>isCountableApartment</code> and nothing else, so the bar can never disagree with the dashboard. The Filters sheet keeps everything it holds today.` },
  ] },
  { part: 'The worker’s task screen', from: 'decisions 6 and 11', items: [
    { n: 6, t: 'One Close job button',
      f: ['src/pages/ContractorPortal.tsx'],
      d: `Remove the <code>data-close-job</code> button rendered in the empty-media branch (the large green one under Files &amp; Photos). The sticky footer button becomes the only way to close a job.` },
    { n: 7, t: 'Urgent loses its box',
      f: ['src/pages/ContractorPortal.tsx'],
      d: `The priority pill is a leaf whose text is “🔴 Urgent” carrying <code>bg-red-50 border border-red-200</code>. Drop the background, the border and the horizontal padding; keep the emoji dot and the word. Do the same for the other priorities so they stay consistent.` },
    { n: 8, t: 'The Download button on the plan works',
      f: ['src/components/plans/PlanAnnotator.tsx'],
      d: `Download must fetch the plan’s bytes through the app’s own <code>/api/drive-fetch</code> route (which pipes rather than buffers) and hand the file to the device — <strong>not</strong> a link to drive.google.com, which turns away a worker who is not signed into Google. Verify on a real phone: this is the one item on the list that cannot be proven in the test container, which has no Drive.` },
    { n: 9, t: 'A closed task says “Job closed” instead of offering the button',
      f: ['src/pages/ContractorPortal.tsx'],
      d: `When <code>assignment.completedAt</code> is set the sticky footer shows a static, non-pressable <strong>Job closed · &lt;time&gt;</strong> in the green family. The message box above it stays live — decision 10 keeps the conversation open.` },
  ] },
  { part: 'Closing a job', from: 'decision 7', items: [
    { n: 10, t: 'Closing becomes a screen of its own',
      f: ['src/pages/ContractorPortal.tsx'],
      d: `Replace the <code>data-closing-panel</code> footer panel with a full surface (<code>fixed inset-0</code>) carrying its own navy header — a back arrow and the apartment name. Two sections only: the existing add-media button with its counter at the top, then one comment box. The footer holds <strong>Send and close the job</strong>. <strong>No separate File section</strong> — the add-media button already takes files. The paperclip and microphone sit <em>inside</em> the comment box at its bottom-right, the same idiom the drawer’s General Notes box uses. <code>arriveClosingRef</code> still applies (it is what stops the sheet’s “a new selection starts outside the closing screen” effect from undoing <code>setClosing(true)</code>), and the finish-early ask still fires on the final press when a task has days left.` },
    { n: 11, t: 'The picture rule follows each worker’s permission',
      f: ['src/pages/ContractorPortal.tsx', 'src/types/index.ts'],
      d: `The line under PICTURES is a string, shown only when <code>!contractor?.photosOptional</code>, and it names <code>MIN_CLOSE_MEDIA</code> rather than a literal 3 — change the constant and the sentence follows. A photos-optional worker sees no line, no counter, and Send is never locked. <strong>Add the key to <code>ContractorUiStrings</code> as optional with a fallback</strong> — those strings are user-edited and stored with no <code>mergeFresh</code>, so a required key renders blank on every object written before today.` },
  ] },
  { part: 'The task as a conversation', from: 'decisions 8, 9 and 10', items: [
    { n: 12, t: 'New shared component: the thread',
      f: ['src/components/tasks/TaskThread.tsx (new)'],
      d: `<strong>One drawing, used in both places</strong> — the owner asked for one conversation on the phone and the computer, and two components would drift. Props: the assignment, its notes, its photos, who is viewing, and <code>readOnly</code>.<br><br>Office messages left, white, 5px top-left corner, author name in accent. Worker messages right, <code>#e3f2fb</code>, 5px top-right corner. A file is a card — type badge, filename, size, “tap to open” — and pressing it downloads and opens through the same <code>/api/drive-fetch</code> route as item 8. A photo is a preview capped near 230px that expands to a lightbox with a Download. Timestamps bottom-right.<br><br><strong>The “Job closed · &lt;time&gt;” marker is DERIVED from <code>assignment.completedAt</code></strong> — never stored as a record. Messages whose <code>createdAt</code> is later than <code>completedAt</code> render below it, which is what keeps the conversation open (decision 10). Nothing in the thread can be edited or deleted.` },
    { n: 13, t: 'The thread in the worker’s portal',
      f: ['src/pages/ContractorPortal.tsx'],
      d: `Replace the FILES &amp; PHOTOS block and the two separate note lists (<code>selOfficeNotes</code> / <code>selContractorNotes</code>) with one <code>&lt;TaskThread&gt;</code> headed <strong>THIS TASK</strong>. The composer beneath it is the existing paperclip + microphone + input + send row. The office’s Add File button leaves this section (owner’s decision — the worker’s paperclip is in the composer and on the closing screen).` },
    { n: 14, t: 'The same thread in the office’s drawer',
      f: ['src/components/apartment/ApartmentDetailDrawer.tsx'],
      d: `Inside the Tasks tab (<code>activeTab === 'tasks'</code>), render the same <code>&lt;TaskThread&gt;</code> under each task card with the office’s identity. Cap the bubbles near 640px on a monitor so they do not run the whole width of the window.` },
    { n: 15, t: 'The closing comment lands in the thread',
      f: ['src/pages/ContractorPortal.tsx', 'src/data/store.ts', 'src/types/index.ts'],
      d: `Add <code>photoIds?: string[]</code> to <code>ContractorNote</code>. <strong>It rides inside <code>contractorNotes</code>, which is already persisted, exported, imported and synced — so the backup trio needs no new entry and the audit stays green.</strong> Sending the closing screen writes ONE contractor note carrying the comment (which may be empty) and the ids of the photos taken on that screen, then completes the assignment. An empty comment still posts the photos and still closes the job.` },
  ] },
];

export const TRAPS = [
  'Every new user-facing string comes from the strings object or it is a bug — and a new <code>ContractorUiStrings</code> key is optional with a fallback, because those objects are user-edited and stored with no merge-fresh.',
  'Width tests are subscribed matchMedia listeners, never values cached at mount. A Fold changes width while a window is open, and anything that caches breaks on it first.',
  'Counts go through <code>isCountableApartment</code> and <code>liveAssignments</code> and nothing else — two places inventing their own totals is a fault this codebase has already paid for twice.',
  '<code>photoIds</code> is the only new field in the whole list, and it rides an existing collection. If anything else gains a state key, it goes into persist + export (top level) + import, and the backup audit is re-run.',
  'The thread must not be built twice. One component, two hosts — the office’s copy and the worker’s copy drifting apart is exactly what the owner asked to avoid.',
  'Nothing here changes the wallboard or the printed sheets. If a change starts reaching into <code>TvPresentationPage</code> or <code>printing.ts</code>, stop — it has gone further than what was approved.',
  'Do not add a file under <code>/api</code>. The Hobby plan allows twelve serverless functions and the folder is full; the plan download in item 8 uses the existing <code>/api/drive-fetch</code>.',
];
