// The CRM CSV import, driven through the real settings card.
//
// A synthetic export (fake families only — the real one holds real customers
// and stays out of the repo) covering every rule: comma and no-comma names,
// a phone missing its Israeli zero, an American phone left alone, each stage
// route, a babysitting row, an unlisted stage, a deal whose Drive folder is
// already a Wolfson apartment's folder (the cross-workspace guard), and a
// full re-import that must plan zero.
import { chromium } from 'playwright';
import { writeFileSync } from 'fs';
import { realisticWolfson, applySeed } from './seed.mjs';

const CSV = `past year
"Generated by Test on Aug 17, 2026 11:49 AM"

Record Count : 10,

Deal Name,Account,Drive URL,Contact Main Phone,Main Number,Stage
"Testberg, Aaron - Install","Testberg, Aaron (Acct)",https://drive.google.com/drive/folders/IMPfolder001,527000001,,Being installed
"Mockstein, Bella - VRF","Mockstein, Bella - VRF",https://drive.google.com/drive/folders/IMPfolder002,+15550001111,,Job Completed
"Fakelov, Chaim - Balance","",https://drive.google.com/drive/folders/IMPfolder003,050-1234567,,Collecting Remaining Balance
Demo Shul - Maintenance,Demo Shul,https://drive.google.com/drive/folders/IMPfolder004,,,Hibernating
"Samplestein, Dov - Deposit","",,,,Collecting Deposit/Key
"Trialman, Ephraim - Geves","",https://drive.google.com/drive/folders/IMPfolder005,,,Installation of Geves
"Wolfson, Tzvika - Repair","",https://drive.google.com/drive/folders/IMPfolder006,,,Job Completed
"Skipper, Gil - Babysit","",,,,Babysitting
"Nothing, Hal - Old","",,,,Not
"Crossed, Ida - Wolfson Tower","",https://drive.google.com/drive/folders/WOLFfolder99,,,Job Completed
`;
writeFileSync('scratchpad/import-test.csv', CSV);

let fails = 0;
function check(ok, label) {
  console.log(`${ok ? 'PASS' : 'FAIL'} ${label}`);
  if (!ok) fails++;
}

const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const blob = await realisticWolfson(browser);
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
await applySeed(ctx, blob);
// Give one WOLFSON apartment the Drive folder the guard must recognise.
// Patched idempotently on every navigation (addInitScript re-runs — the
// standing harness trap), through the same localStorage the app reads.
await ctx.addInitScript(() => {
  const raw = localStorage.getItem('wolfson_app_data');
  if (!raw) return;
  const d = JSON.parse(raw);
  const apt = (d.apartments ?? []).find(a => a.id === 'A1-1');
  if (apt && !apt.driveLink) {
    apt.driveLink = 'https://drive.google.com/drive/folders/WOLFfolder99';
    localStorage.setItem('wolfson_app_data', JSON.stringify(d));
  }
});

const page = await ctx.newPage();
await page.goto('http://localhost:5173/project');
await page.waitForTimeout(1600);

// To the Job Board, the way a person goes — a hand-written localStorage
// patch is flushed over on unload.
await page.locator('header button', { hasText: /Wolfson/ }).first().click();
await page.waitForTimeout(400);
await page.getByRole('menu').getByText(/Job Board/).first().click();
await page.waitForTimeout(2000);

// ── the preview ───────────────────────────────────────────────────────────
await page.goto('http://localhost:5173/settings');
await page.waitForTimeout(1200);
check(await page.getByText('Import jobs from a CSV').count() > 0, 'import card is on the Job Board settings');

await page.locator('input[type="file"][accept*="csv"]').setInputFiles('scratchpad/import-test.csv');
await page.waitForTimeout(700);

const importedChip = await page.getByText(/\d+ will be imported/).first().textContent();
check(importedChip?.trim() === '7 will be imported', `preview plans 7 (${importedChip?.trim()})`);
check(await page.getByText('3 skipped', { exact: false }).count() > 0, 'preview skips 3');
check(await page.getByText(/Apply will also create/).count() > 0, 'preview names the stages and group it will create');

// The guard's work is visible: open the skipped list, find the Wolfson reason.
// getByRole, not getByText(/skipped/) — the card's own blurb also says
// "is skipped" and a text match clicks the paragraph instead of the button.
await page.getByRole('button', { name: /\d+ skipped/ }).click();
await page.waitForTimeout(300);
check(await page.getByText(/Drive folder belongs to Wolfson/).count() > 0, 'cross-workspace skip says whose folder it is');
check(await page.getByText(/left out for now/).count() > 0, 'babysitting skip reason shown');

// Sections per destination.
for (const sec of ['Done group', 'Ready to Start group', 'Open board', 'Currently in Geves group']) {
  check(await page.getByText(sec, { exact: false }).count() > 0, `section: ${sec}`);
}

// ── apply ─────────────────────────────────────────────────────────────────
await page.getByRole('button', { name: /^Import 7 jobs$/ }).click();
await page.waitForTimeout(1500);
check(await page.getByText(/7 jobs imported/).count() > 0, 'apply reports 7 imported');

// What actually landed, read from the app's own persisted state.
const state = await page.evaluate(() => {
  const d = JSON.parse(localStorage.getItem('general_app_data') ?? '{}');
  const jobs = (d.apartments ?? []).filter(a => a.id.startsWith('G-imp-'));
  const stages = (d.stages ?? []).filter(s => s.projectId === 'general').map(s => s.name);
  const bins = (d.canvasElements ?? []).filter(e => e.type === 'bin');
  return {
    jobs: jobs.map(j => ({
      name: j.displayName, bin: j.boardBin ?? '', phone: j.phone ?? '',
      drive: j.driveLink ?? '', stageId: j.currentStageId, notes: j.generalNotes,
    })),
    stages,
    customBins: bins.filter(b => !b.binKind).map(b => b.text),
    stageById: Object.fromEntries((d.stages ?? []).map(s => [s.id, s.name])),
  };
});
check(state.jobs.length === 7, `7 jobs in the store (${state.jobs.length})`);

const byName = Object.fromEntries(state.jobs.map(j => [j.name, j]));
check(byName['Testberg']?.bin === '' && state.stageById[byName['Testberg']?.stageId] === 'AC installation',
  'Testberg: open board, stage AC installation');
check(byName['Testberg']?.phone === '0527000001', `Israeli phone got its zero (${byName['Testberg']?.phone})`);
check(byName['Mockstein']?.bin === 'done' && state.stageById[byName['Mockstein']?.stageId] === 'Job completed',
  'Mockstein: Done group, stage Job completed');
check(byName['Mockstein']?.phone === '+15550001111', 'American phone untouched');
check(byName['Fakelov']?.bin === 'done', 'Collecting Remaining Balance filed into Done');
check(byName['Demo Shul']?.bin === 'ready', 'no-comma name kept whole, into Ready to Start');
check(byName['Samplestein']?.bin === 'ready', 'Collecting Deposit/Key into Ready to Start');
check(byName['Wolfson']?.bin === 'done', 'the FAMILY called Wolfson imported (name is only a warning)');
check(!byName['Crossed'], 'the deal with the Wolfson apartment folder was NOT imported');
const geves = state.jobs.find(j => j.name === 'Trialman');
check(!!geves && geves.bin.startsWith('CE-bin-') && state.stageById[geves.stageId] === 'Installation of Geves',
  'Geves job filed into the new group with its stage');
check(state.customBins.includes('Currently in Geves'), 'the "Currently in Geves" group exists');
check(byName['Testberg']?.notes.startsWith('Testberg, Aaron - Install'), 'full deal name kept in the notes');
check(byName['Testberg']?.notes.includes('Account: Testberg, Aaron (Acct)'), 'account kept when it adds anything');
check(!byName['Mockstein']?.notes.includes('Account:'), 'account dropped when it repeats the deal name');

// ── the board shows it ────────────────────────────────────────────────────
await page.goto('http://localhost:5173/jobs');
await page.waitForTimeout(1600);
check(await page.getByText('Testberg').count() > 0, 'the open-board tile is on the board');

// The drawer: phone rides with the job and can be dialled.
// DOUBLE-click — on the board a single mouse click SELECTS (the "I mean this
// one" gesture); double-click is what opens, by design.
await page.getByText('Testberg').first().dblclick();
await page.waitForTimeout(1100);
const drawerOpen = await page.locator('.drawer-panel').count();
if (!drawerOpen) await page.screenshot({ path: 'scratchpad/import-drawer-fail.png' });
check(drawerOpen > 0, 'double-clicking the tile opened the job');
const phoneVal = await page.locator('.drawer-panel input[placeholder="Phone"]').first().inputValue().catch(() => '');
check(phoneVal === '0527000001', `drawer shows the phone (${phoneVal})`);
check(await page.locator('a[href="tel:0527000001"]').count() > 0, 'tap-to-call link');
await page.keyboard.press('Escape');

// ── re-import: the same file must plan nothing ────────────────────────────
await page.goto('http://localhost:5173/settings');
await page.waitForTimeout(1100);
await page.locator('input[type="file"][accept*="csv"]').setInputFiles('scratchpad/import-test.csv');
await page.waitForTimeout(700);
const again = await page.getByText(/\d+ will be imported/).first().textContent();
check(again?.trim() === '0 will be imported', `re-import plans nothing (${again?.trim()})`);
await page.getByRole('button', { name: /\d+ skipped/ }).click();
await page.waitForTimeout(300);
check(await page.getByText(/already on the board \(same Drive folder\)/).count() > 0, 're-import says why: already on the board');

console.log(fails === 0 ? '\nALL PASS' : `\n${fails} FAILURES`);
await browser.close();
process.exit(fails ? 1 : 0);
