import { extractFolderId } from './driveApi';

/**
 * Importing the CRM's deal export onto the Job Board.
 *
 * Everything in here is PURE — no store, no DOM, no network — because the
 * office will run this against next quarter's export too, and the only way to
 * trust a 600-row import is to have tested the arithmetic against a real file
 * offline. The UI card (ImportJobsCard) owns all the writing.
 *
 * The export this was built against is Zoho's: a title line, a "Generated by"
 * line, a record count, a blank line, and THEN the real header. The parser
 * finds the header by looking for the "Deal Name" column rather than assuming
 * a line number, so a plain export with no preamble works too.
 */

// ── CSV ─────────────────────────────────────────────────────────────────────

/** One data row, keyed by the header names we care about. */
export interface CrmRow {
  dealName: string;
  account: string;
  driveUrl: string;
  /** First non-empty of "Contact Main Phone" / "Main Number", untouched. */
  rawPhone: string;
  stage: string;
}

/**
 * A real quoted-CSV walk — split(',') dies on the first "Korn, Aryeh".
 * Handles quoted fields, doubled quotes inside them, and \r\n endings.
 */
export function parseCsv(text: string): string[][] {
  const rows: string[][] = [];
  let row: string[] = [];
  let field = '';
  let inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; }
        else inQuotes = false;
      } else field += c;
    } else if (c === '"') {
      inQuotes = true;
    } else if (c === ',') {
      row.push(field); field = '';
    } else if (c === '\n' || c === '\r') {
      if (c === '\r' && text[i + 1] === '\n') i++;
      row.push(field); field = '';
      rows.push(row); row = [];
    } else field += c;
  }
  if (field !== '' || row.length) { row.push(field); rows.push(row); }
  return rows;
}

/** Pull the deal rows out of a Zoho export, preamble and all. */
export function parseZohoCsv(text: string): CrmRow[] {
  const rows = parseCsv(text.replace(/^﻿/, ''));
  const hi = rows.findIndex(r => r.some(c => c.trim().toLowerCase() === 'deal name'));
  if (hi === -1) return [];
  const header = rows[hi].map(c => c.trim().toLowerCase());
  const col = (name: string) => header.indexOf(name);
  const iDeal = col('deal name');
  const iAccount = col('account');
  const iDrive = col('drive url');
  const iPhone1 = col('contact main phone');
  const iPhone2 = col('main number');
  const iStage = col('stage');
  const out: CrmRow[] = [];
  for (const r of rows.slice(hi + 1)) {
    const dealName = (r[iDeal] ?? '').trim();
    if (!dealName) continue;
    const p1 = iPhone1 >= 0 ? (r[iPhone1] ?? '').trim() : '';
    const p2 = iPhone2 >= 0 ? (r[iPhone2] ?? '').trim() : '';
    out.push({
      dealName,
      account: iAccount >= 0 ? (r[iAccount] ?? '').trim() : '',
      driveUrl: iDrive >= 0 ? (r[iDrive] ?? '').trim() : '',
      rawPhone: p1 || p2,
      stage: iStage >= 0 ? (r[iStage] ?? '').trim() : '',
    });
  }
  return out;
}

// ── Field rules ─────────────────────────────────────────────────────────────

/**
 * The family name is what goes on the tile: the part before the comma
 * ("Korn, Aryeh - Filter Cleaning" → "Korn"). About one deal in six has no
 * comma — institutions and a few "Family First - Job" names — and for those
 * the name is everything before the first " - ", which is the same rule the
 * app already applies to Drive folder titles (familyNameFromFolderName).
 */
export function familyFromDeal(deal: string): string {
  const t = deal.trim();
  const comma = t.indexOf(',');
  if (comma > 0) return t.slice(0, comma).trim();
  const dash = t.search(/\s-[\s]/);
  if (dash > 0) return t.slice(0, dash).trim();
  return t;
}

/**
 * The CRM strips the leading zero off some Israeli numbers. Put it back —
 * and ONLY there. Anything international (+…), anything already starting
 * with 0, and anything American (leading 1, or a bare 10+ digit number,
 * which no Israeli number is once the zero is missing) is left exactly as
 * typed. An Israeli number missing its zero has at most 9 digits.
 */
export function normalizePhone(raw: string): string {
  const p = raw.trim();
  if (!p) return '';
  if (p.startsWith('+')) return p;
  const first = p[0];
  if (first === '0' || first === '1') return p;
  const digits = p.replace(/\D/g, '');
  if (digits.length > 0 && digits.length <= 9) return '0' + p;
  return p;
}

// ── Routing ─────────────────────────────────────────────────────────────────

/** Where a deal lands: the open board, a built-in group, or a named group. */
export interface Route {
  /** '' = the open board; 'done' / 'ready' = built-in groups; anything else = a group by that NAME. */
  group: '' | 'done' | 'ready' | string;
  /** Stage NAME to set (resolved to an id — created if missing — at apply time). */
  stageName: string | null;
}

/**
 * The owner's mapping, stage by stage, as decided on 2026-08-17.
 * CRM stages not in this table are not imported (babysitting deliberately so
 * — "don't put in yet"). Keys are lower-cased CRM stage names.
 */
export const STAGE_ROUTES: Record<string, Route> = {
  'job completed':                { group: 'done', stageName: 'Job completed' },
  'collecting remaining balance': { group: 'done', stageName: 'Job completed' },
  'collecting extras':            { group: 'done', stageName: 'Job completed' },
  'hibernating':                  { group: 'ready', stageName: null },
  'collecting deposit/key':       { group: 'ready', stageName: null },
  'being installed':              { group: '', stageName: 'AC installation' },
  'installation of geves':        { group: 'Currently in Geves', stageName: 'Installation of Geves' },
};

/** What the preview shows for each group key. */
export function routeLabel(route: Route): string {
  if (route.group === '') return 'Open board';
  if (route.group === 'done') return 'Done group';
  if (route.group === 'ready') return 'Ready to Start group';
  return `${route.group} group`;
}

// ── Planning ────────────────────────────────────────────────────────────────

export interface PlannedJob {
  dealName: string;
  account: string;
  family: string;
  driveUrl: string;
  folderId: string | null;
  phone: string;
  crmStage: string;
  route: Route;
  /** Things worth a human glance before Apply. Never blocks on its own. */
  warnings: string[];
}

export interface SkippedRow {
  dealName: string;
  crmStage: string;
  reason: string;
}

export interface ImportPlan {
  planned: PlannedJob[];
  skipped: SkippedRow[];
  /** Stage names the workspace does not have yet and Apply would create. */
  stagesToCreate: string[];
  /** Group names (beyond the built-ins) Apply would create. */
  groupsToCreate: string[];
}

export interface PlanContext {
  /**
   * Drive folder id → workspace name, for every OTHER workspace's apartments.
   * The check the owner asked for by name: a deal whose Drive folder is
   * already some apartment's folder in Wolfson or Netiv is that workspace's
   * job wearing a CRM row, and must not become a board tile.
   */
  otherWorkspaceFolders: Map<string, string>;
  /** Drive folder ids already on jobs in THIS workspace — re-running the import must not duplicate. */
  existingFolderIds: Set<string>;
  /** Full deal names already recorded on existing jobs (their notes), lower-cased. For rows with no Drive link. */
  existingDealNames: Set<string>;
  /** Names of stages that already exist for this workspace, as typed. */
  existingStageNames: string[];
  /** Labels of groups that already exist on the board (custom bins). */
  existingGroupNames: string[];
}

const OTHER_WORKSPACE_NAME = /wolfson|netiv|neve shamir/i;

/**
 * Turn CRM rows into a plan the office can read before anything is written.
 *
 * Order of decisions per row, most final first: not in the mapping → skipped;
 * Drive folder belongs to another workspace → skipped (the guard); already on
 * the board → skipped (re-running an import is safe); otherwise planned, with
 * warnings for the things only a person can judge — a NAME that mentions
 * another workspace is a warning rather than a skip, because "Wolfson, Tzvika"
 * is a family called Wolfson, not the tower.
 */
export function planImport(rows: CrmRow[], ctx: PlanContext): ImportPlan {
  const planned: PlannedJob[] = [];
  const skipped: SkippedRow[] = [];
  const seenFolders = new Map<string, string>(); // folder id → family already planned this run

  for (const row of rows) {
    const route = STAGE_ROUTES[row.stage.toLowerCase()];
    if (!route) {
      skipped.push({ dealName: row.dealName, crmStage: row.stage, reason: skipReason(row.stage) });
      continue;
    }
    const folderId = row.driveUrl ? extractFolderId(row.driveUrl) : null;
    if (folderId) {
      const owner = ctx.otherWorkspaceFolders.get(folderId);
      if (owner) {
        skipped.push({ dealName: row.dealName, crmStage: row.stage, reason: `Drive folder belongs to ${owner}` });
        continue;
      }
      if (ctx.existingFolderIds.has(folderId)) {
        skipped.push({ dealName: row.dealName, crmStage: row.stage, reason: 'already on the board (same Drive folder)' });
        continue;
      }
    } else if (ctx.existingDealNames.has(row.dealName.toLowerCase())) {
      skipped.push({ dealName: row.dealName, crmStage: row.stage, reason: 'already on the board (same deal name)' });
      continue;
    }

    const warnings: string[] = [];
    const m = row.dealName.match(OTHER_WORKSPACE_NAME);
    if (m) warnings.push(`name mentions "${m[0]}" — check it is not that workspace's job`);
    if (!folderId) warnings.push('no Drive link');
    if (folderId) {
      const dup = seenFolders.get(folderId);
      if (dup) warnings.push(`same Drive folder as "${dup}"`);
      else seenFolders.set(folderId, familyFromDeal(row.dealName));
    }

    planned.push({
      dealName: row.dealName,
      account: row.account,
      family: familyFromDeal(row.dealName),
      driveUrl: row.driveUrl,
      folderId,
      phone: normalizePhone(row.rawPhone),
      crmStage: row.stage,
      route,
      warnings,
    });
  }

  const stageNamesLower = new Set(ctx.existingStageNames.map(n => n.trim().toLowerCase()));
  const stagesToCreate = [...new Set(
    planned.map(p => p.route.stageName).filter((n): n is string => !!n && !stageNamesLower.has(n.toLowerCase()))
  )];
  const groupNamesLower = new Set(ctx.existingGroupNames.map(n => n.trim().toLowerCase()));
  const groupsToCreate = [...new Set(
    planned.map(p => p.route.group)
      .filter(g => g && g !== 'done' && g !== 'ready' && !groupNamesLower.has(g.toLowerCase()))
  )];

  return { planned, skipped, stagesToCreate, groupsToCreate };
}

function skipReason(stage: string): string {
  const s = stage.toLowerCase();
  if (s === 'babysitting') return 'left out for now, as asked';
  if (s === 'closed lost') return 'closed lost';
  if (s === 'collecting information' || s === 'creating proposal') return 'skipped, as asked';
  return 'stage not in the import list';
}
